movie_titles = [
    "Avengers: Endgame",
    "Avengers: Infinity War",
    "The Avengers",
    "Avengers: Age of Ultron",
    "Iron Man",
    "Thor: Ragnarok",
    "Captain America: Civil War",
    "Guardians of the Galaxy Vol. 3",
    "Spider-Man: No Way Home",
    "Spider-Man: Far From Home",
    "Spider-Man: No Way Home",
    "The Amazing Spider-Man",
    "The Amazing Spider-Man 2",
    "Spider-Man: Homecoming",
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "Schindler's List",
    "The Lord of the Rings: The Return of the King",
    "Forrest Gump",
    "Fight Club",
    "Inception",
    "The Matrix",
    "Goodfellas",
    "The Empire Strikes Back",
    "One Flew Over the Cuckoo's Nest",
    "Seven Samurai",
    "City of God",
    "The Silence of the Lambs",
    "It's a Wonderful Life",
    "Life Is Beautiful",
    "The Usual Suspects",
    "Se7en",
    "The Lion King",
    "The Departed",
    "Gladiator",
    "Terminator 2: Judgment Day",
    "Back to the Future",
    "Whiplash",
    "The Prestige",
    "The Intouchables",
    "The Green Mile",
    "Parasite",
    "The Pianist",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Interstellar",
    "Jaws",
    "Django Unchained",
    "The Shining",
    "WALL-E",
    "The Dark Knight Rises",
    "The Great Dictator",
    "Raiders of the Lost Ark",
    "The Social Network",
    "Casablanca",
    "Amélie",
    "Saving Private Ryan",
    "Spirited Away",
    "The Seven Year Itch",
    "12 Angry Men",
    "Alien",
    "The Truman Show",
    "The Breakfast Club",
    "The Grand Budapest Hotel",
    "The Thing",
    "Braveheart",
    "A Clockwork Orange",
    "The Lion in Winter",
    "The Sixth Sense",
    "The Big Lebowski",
    "Raging Bull",
    "No Country for Old Men",
    "Memento",
    "La La Land",
    "Mad Max: Fury Road",
    "Trainspotting",
    "Zootopia",
    "The Shape of Water",
    "The Hateful Eight",
    "Moonlight",
    "The Revenant",
    "Arrival",
    "The Wolf of Wall Street",
    "Get Out",
    "Black Panther",
    "Her",
    "A Beautiful Mind",
    "The Secret in Their Eyes",
    "The Curious Case of Benjamin Button",
    "Gravity",
    "Dead Poets Society",
    "Finding Nemo",
    "The Wizard of Oz",
    "The Graduate",
    "The Maltese Falcon",
    "The King’s Speech",
    "The Nightmare Before Christmas",
    "The Incredibles",
    "Hacksaw Ridge",
    "1917",
    "The Artist",
    "The Favourite",
    "Coco",
    "The Best Years of Our Lives",
    "The Exorcist",
    "Stand by Me",
    "The Thing",
    "The Departed",
    "A Star is Born",
    "The Sound of Music",
    "The Iron Giant",
    "Finding Dory",
    "The Lego Movie",
    "Inside Out",
    "The Shape of Water",
    "Roma",
    "Birdman",
    "Phantom Thread",
    "The Master",
    "The Blair Witch Project",
    "Dances with Wolves",
    "Philadelphia",
    "The Color Purple",
    "Good Will Hunting",
    "The Dark Knight",
    "No Country for Old Men",
    "The Big Short",
    "The Favourite",
    "12 Years a Slave",
    "Boyhood",
    "The King's Speech",
    "Hidden Figures",
    "A Star Is Born",
    "The Irishman",
    "Joker",
    "Ford v Ferrari",
    "Knives Out",
    "Marriage Story",
    "Little Women",
    "1917",
    "Parasite",
    "The Lighthouse",
    "Uncut Gems",
    "Midsommar",
    "Jojo Rabbit",
    "Tenet",
    "Soul",
    "Promising Young Woman",
    "Dune",
    "Spider-Man: No Way Home",
    "Shang-Chi and the Legend of the Ten Rings",
    "A Quiet Place",
    "Zombieland",
    "The Cabin in the Woods",
    "Hereditary",
    "Get Out",
    "The Invisible Man",
    "The Conjuring",
    "Scream",
    "The Witch",
    "Saw",
    "Insidious",
    "The Babadook",
    "A Quiet Place Part II",
    "Midsommar",
    "Candyman",
    "The Autopsy of Jane Doe",
    "The Cabin in the Woods",
    "Train to Busan",
    "The Descent",
    "Happy Death Day",
    "Don't Breathe",
    "28 Days Later",
    "It",
    "The Ring",
    "Misery",
    "The Others",
    "The Orphanage",
    "The Grudge",
    "The Nun",
    "Hereditary",
    "A Nightmare on Elm Street",
    "The Exorcism of Emily Rose",
    "Get Out",
    "The Texas Chain Saw Massacre",
    "Pet Sematary",
    "Child's Play",
    "Sinister",
    "The Shining",
    "Carrie",
    "The Purge",
    "The Conjuring 2",
    "Insidious: Chapter 2",
    "Annabelle",
    "Paranormal Activity",
    "Halloween",
    "The Amityville Horror",
    "The Fly",
    "The Witch",
    "The Invitation",
    "The Host",
    "The Conjuring: The Devil Made Me Do It",
    "10 Cloverfield Lane",
    "The Possession",
    "The Grudge",
    "Pet Sematary",
    "The Invisible Man",
    "The Strangers",
    "Candyman",
    "A Quiet Place Part II",
    "Ready or Not",
    "Freaky",
    "Malignant",
    "Scary Stories to Tell in the Dark",
    "Truth or Dare",
    "The Curse of La Llorona",
    "The Night House",
    "The Conjuring: The Devil Made Me Do It",
    "Old",
    "Midsommar",
    "The Forever Purge",
    "Fear Street Trilogy",
    "Last Night in Soho",
    "The Lodge",
    "The Night House",
    "The Dark and the Wicked",
    "The Conjuring: The Devil Made Me Do It",
    "Spiral: From the Book of Saw",
    "A Quiet Place Part II",
    "The Medium",
    "Escape Room",
    "Bird Box",
    "The Haunting of Hill House",
    "The Outsider",
    "Servant",
    "The Terror",
    "Channel Zero",
    "Midnight Mass",
    "The Walking Dead",
    "Stranger Things",
    "American Horror Story",
    "The Haunting of Bly Manor",
    "Castle Rock",
    "Lovecraft Country",
    "Bates Motel",
    "Penny Dreadful",
    "The X-Files",
    "The Twilight Zone",
]
